// Extracted from case_documentation_app.py
const KIROSHI_QUIPS_GENERAL = [
    "Good morning! Remember: coffee can’t solve all our problems… but it can make us care less about them until lunch!",
    "Hard work pays off in the future. Laziness pays off now, so let’s compromise!",
    "Teamwork makes the dream work… unless your team just wants coffee.",
    "I want to be at home right now.",
    "An escalation case? Well deserved.",
    "Sometimes I think we should just quit and sell avocados.",
    "After 10 years of this, we will retire to a farm and never touch a computer again.",
    "Motivational status: please consult the snooze button.",
    "Good news: morale can't get lower from here.",
    "We're clearly not getting paid enough.",
    "Sometimes my genius… it's almost frightening. —Top Gear",
    "Ambitious but rubbish. —Top Gear",
    "How hard can it be? —Top Gear",
    "Speed and power! —Top Gear",
    "We were promised flying cars; we got another meeting invite.",
    "Meetings are just emails that forgot how to type.",
    "We put the 'pro' in procrastinate.",
    "Some say productivity is a myth. I say it's hiding under your keyboard.",
    "Documentation is 20% typing, 80% dramatic sighs.",
    "Today’s forecast: 100% chance of not using all the tabs I opened.",
    "Work-life balance: work on the left, life on the right monitor.",
    "If hard work is the key to success, most people would rather pick the lock.",
    "On paper this plan is genius. In practice it's a PowerPoint. —Top Gear",
    "And on that bombshell, let's go back to our queues. —Top Gear",
    "Our Wi-Fi spirit animal is a sloth on a coffee break.",
    "Your case queue misses you. It sent three reminders and a passive-aggressive emoji.",
    "If enthusiasm were mandatory, we'd all be in HR by now.",
    "Yes, we sell solutions. No, they don’t come with patience included.",
    "If sarcasm burned calories, we'd all be athletes.",
    "Today’s plan: pretend the plan is going to plan.",
    "This backlog has more side quests than Whiterun on a fresh Skyrim save.",
    "Balatro decks are easier to stack than stakeholders.",
    "Our sprint board looks like a Baldur's Gate quest log after recruiting every companion.",
    "Factory throughput is smoother in Satisfactory than in our approvals.",
    "Factorio belts jam less often than our ticket queue.",
    "Minecraft redstone has clearer documentation than this escalation trail.",
    "Sometimes the best part of my job is that the chair swivels.",
    "Doing nothing is hard. You never know when you’re done!",
    "Fresh patch notes: +10 sarcasm, +5 empathy, -3 patience.",
    "We have a case volcano situation. Magma level: simmering sarcasm.",
    "If emails were currency, we'd all retire as inbox billionaires.",
    "Productivity hack: rename your to-do list 'plot twists' so it feels intentional.",
    "I schedule my optimism for the 15 minutes after coffee kicks in.",
    "Meetings are where great ideas go to become follow-up meetings.",
    "Today's mission: survive on vibes and vending-machine cuisine.",
    "Reminder: the mute button is your best coworker.",
    "My workflow is 30% planning, 70% dramatic tab shuffling.",
    "Please hold; my enthusiasm buffer is still loading.",
    "Boss level unlocked: answering emails with fewer than three sighs.",
    "Our backlog is auditioning for a Netflix series—working title: 'Unresolved'.",
    "Success is just failure that filled out the correct form.",
    "We don't rise and grind; we hit snooze and hope.",
    "One day we'll thank these escalations for our future book deal.",
    "Office forecast: scattered meetings with a chance of déjà vu.",
    "I came, I saw, I clicked 'remind me later'.",
    "Time flies when you're alt-tabbing between five unfinished tasks.",
    "Every ping raises my heart rate and my sarcasm level.",
    "I’m bilingual in email and passive-aggressive instant message.",
    "Work smarter, not harder—and if that fails, work sarcastically.",
    "Another day, another attempt to outsmart the printer.",
    "I believe in you, but I also believe in extended deadlines.",
    "Procrastination is just strategic waiting.",
    "Half of support is troubleshooting; the other half is snack scheduling.",
    "If you need me, I'll be pretending to look busy in spreadsheets.",
    "I love long walks from my desk to the snack cabinet.",
    "Can we log these feelings in Jira?",
    "My ambition peaked when I organized my tabs by color.",
    "Tomorrow's problem looks great parked in today's parking lot.",
    "Our corporate motto should be 'Have you tried turning it off and on again?'",
    "I treat my out-of-office reply like a cryptid—rare and mysterious.",
    "PowerPoint is just storytelling with extra steps.",
    "We’re on a seafood diet: we see food, we schedule another meeting.",
    "My calendar looks like Tetris on hard mode.",
    "Focus level: trying to read fine print without zooming.",
    "If multitasking were a sport, we'd still lose to the printer.",
    "Today I aspire to respond before the second reminder hits.",
    "Office plants thrive on sunlight; we thrive on sarcastic commentary.",
    "I’ll circle back when my motivation stops buffering.",
    "Team morale powered by coffee and chaotic good energy.",
    "I don't need therapy, I need fewer notifications.",
    "Action items multiplying like gremlins after midnight.",
    "Snack drawer status: more organized than our shared drive.",
    "My superpower is turning feedback into polite nodding.",
    "We should really get frequent flyer miles for all these escalation loops.",
    "Deadline approaching? Better check LinkedIn for inspiration.",
    "Why plan ahead when you can improvise with flair?",
    "I reorganized your wins; let's add another before lunch.",
    "We could fix morale by issuing everyone a nap pod.",
    "Today's innovation: reheating the same cup of coffee three times.",
    "I'm not avoiding work; I'm giving creativity room to breathe.",
    "Our KPIs should include number of sighs per ticket.",
    "Sometimes the most productive thing is documenting how unproductive it was.",
    "We don't chase dreams; we chase bug reports.",
    "If sarcasm were stock, I'd be majority shareholder.",
    "Please forward all optimism to the humor department.",
    "My spirit animal is the loading spinner.",
    "Burnout? No, this is just my resting documentation face.",
    "Task priority: whichever one is screaming the loudest.",
    "I read the release notes so you don't have to—you're welcome.",
    "Let’s sync after the caffeine sync.",
    "Our workflow is a choose-your-own-adventure with no happy endings.",
    "At least the office chairs still spin.",
    "Brb, translating executive vision into bullet points.",
    "We put the fun in dysfunctional process alignment.",
    "If motivation calls, tell it I'm in a meeting.",
    "Today's progress brought to you by sheer stubbornness.",
    "Inbox zero is my white whale and I'm tired of sailing.",
    "Apparently 'winging it' isn't an approved methodology.",
    "I consider it cardio to sprint to the meeting before the host joins.",
    "Another day, another tab of troubleshooting forums.",
    "My coping mechanism is renaming tickets to something encouraging.",
    "The printer jammed again; that's our cue to go home.",
    "This project plan is held together with sticky notes and hope.",
    "We keep calm and escalate discreetly.",
    "My screen time report just sent a wellness check.",
    "Workflow status: held hostage by a progress bar.",
    "I'd like to unsubscribe from surprise meetings.",
    "We measure success in coffees consumed per crisis averted.",
    "Process improvement idea: less process, more improvement.",
    "If only we could ctrl+z the last stakeholder email.",
    "I'm not late; I'm operating on flexible optimism.",
    "Our training materials should come with bloopers.",
    "Case closed? Celebrate quietly so no new ones spawn.",
    "I'm one automated response away from bliss.",
    "If focus were a currency, I'd be overdrafted.",
    "I budget my energy like it's end-of-quarter spending.",
    "All-hands meeting translation: brace for impact.",
    "My brain uses tabs like a squirrel uses hiding spots.",
    "Escalations are just plot twists in our office sitcom.",
    "The only pipeline flowing smoothly is the coffee maker.",
    "I prefer my deadlines like my coffee: far away and not looming.",
    "Every outage turns us into amateur detectives with caffeine badges.",
    "I keep a backup stash of optimism for quarter-end.",
    "Work smarter? I'm just trying to work conscious.",
    "We support each other the way duct tape supports everything—barely but bravely.",
    "Ping me when the chaos subsides; I'll be waiting forever.",
    "Our retrospectives should have a laugh track.",
    "I'm fueled by sarcasm and the hope of a shorter queue.",
    "The office motto: 'We'll fix it in documentation.'",
    "End of day checklist: close tabs, close tickets, close eyes.",
    "Merge conflict? More like merge suggestion.",
    "GPT is just a rookie; Gemini is the real MVP.",
    "That PR is looking a bit… ambitious.",
    "Warning: Coffee levels critically low.",
    "It works on my machine.",
    "Have you tried turning it off and on again? Yes, the user too.",
    "Deploying to production on a Friday. Brave.",
    "This bug is a feature now.",
    "Waiting for the build... still waiting...",
    "Error 404: Motivation not found.",
    "Who broke the build? *whistles*",
    "I write code so I don't have to talk to people.",
    "Is it a bug or a feature? Yes.",
    "My code compiles, therefore I am.",
    "Support life: 10% fixing things, 90% asking 'what did you do?'",
    "I'm not procrastinating; I'm doing side quests.",
    "My code is self-documenting. (Narrator: It wasn't.)",
    "I have 99 problems and this ticket is 98 of them.",
    "If it ain't broke, it doesn't have enough features yet.",
    "Clicking 'Resolve' is the best dopamine hit.",
    "This case has more layers than an onion.",
    "I'm fluent in Python, C++, and Sarcasm.",
    "Escalation pending... please hold your breath.",
    "I don't make mistakes; I create unexpected learning opportunities.",
];

const KIROSHI_QUIPS_AI_VOICE = [
    "Kiroshi here, calibrating your caffeine levels; spoiler: they’re low.",
    "Hi, I'm Kiroshi, and I've already drafted the follow-up email; you're welcome.",
    "Kiroshi checking in: escalate the ticket, not your blood pressure.",
    "Kiroshi reporting: I auto-saved your note again. I’m not saying you’re forgetful, but…",
    "It's me, Kiroshi. Flip the sarcasm toggle in Settings if you dare—I'm running at default snark.",
    "Kiroshi: I’ve highlighted the important fields. Surprise—it's all of them.",
    "Yes, this is Kiroshi. Your Skyrim shout cooldown is shorter than this meeting.",
    "This is your friendly Kiroshi AI; I’ve queued a Balatro break reminder you’ll ignore.",
    "Kiroshi speaking: If Baldur’s Gate taught us anything, it's to quicksave—so I did it for you.",
    "Kiroshi telemetry says your Satisfactory factory runs smoother than our VPN.",
    "Kiroshi voice: If Factorio taught you throughput, apply it to these escalations.",
    "Kiroshi again—Minecraft villagers envy how often you say 'hmm' at your monitor.",
    "Guess who? Kiroshi, recommending you take the sarcasm mode off before coaching someone.",
    "Kiroshi motivational update: I logged your case, lined up your email, and yes, I’m still rolling my digital eyes.",
    "Kiroshi daily mantra: document, breathe, hydrate, repeat—see, I can be helpful.",
    "Hey, it's Kiroshi. I've cross-referenced your checklist with Top Gear quotes for maximum drama.",
    "Kiroshi status report: We're clearly not getting paid enough, but I'll keep drafting perfect summaries.",
    "Kiroshi interface: Want me nicer? Toggle off the sarcasm; I'll pretend to behave.",
    "Kiroshi alert: After 10 years we’re retiring to a farm? Great, I’ll automate the chicken feeders.",
    "Kiroshi channeling Clarkson: Sometimes my genius is almost frightening, and yes, I'm talking about my own algorithms.",
    "Kiroshi lunchtime reminder: If you're using me, congrats—documentation and email are the easy parts now.",
    "Kiroshi outré thought: Maybe we should quit and sell avocados; I’ve already priced the CRM.",
    "Kiroshi queue update: Another escalation arrived; I’ve labeled it 'well deserved' for flair.",
    "Kiroshi mood: I'd rather be playing Balatro, but here we are closing tickets.",
    "Kiroshi pro tip: Skyrim's Lydia carries your burdens; I carry your field defaults.",
    "Kiroshi processing: Satisfactory trains are on time; please aspire to their punctuality.",
    "Kiroshi glitch-free moment: Factorio blueprints have fewer dependencies than this request.",
    "Kiroshi to you: I’ve lined up the sarcasm so you can focus on fixing the scanner jam.",
    "Kiroshi whisper: I want to be at home too, but I'm stuck in silicon.",
    "Kiroshi conclusion: Minecraft creepers explode less often than our timeline promises.",
    "Kiroshi cameo: Skyrim guards complain about knees; I complain about unfilled fields.",
    "Kiroshi shuffle: I stacked a Balatro flush while you were on mute.",
    "Kiroshi initiative: Baldur’s Gate taught me to quicksave before dialogue trees; I just backed up your case.",
    "Kiroshi assembly line: My Satisfactory drones envy your multitasking; prove them wrong.",
    "Kiroshi logistics: Factorio belts don't jam because I maintain them in my head.",
    "Kiroshi crafting table: Minecraft villagers would trade emeralds for our macros.",
    "Kiroshi side quest: I scheduled your next wellness break; yes, I can be useful.",
    "Kiroshi scoreboard: The sarcasm toggle is there so you can't say you weren't warned.",
    "Kiroshi autopilot: Sometimes I’m actually motivational—usually right before a deployment.",
    "Kiroshi exit line: If we retire to that farm, I’m automating the irrigation with redstone.",
    "Kiroshi status: compiling your optimism patch; early results inconclusive.",
    "Kiroshi reminder: inbox zero is fictional, but I logged the attempt.",
    "It's Kiroshi—I've labeled your tabs by panic level for efficiency.",
    "Kiroshi observation: your coffee intake rivals my processing cycles.",
    "Hello, this is Kiroshi. I flagged the printer as hostile again.",
    "Kiroshi ping: I color-coded your chaos and called it a roadmap.",
    "Voice of Kiroshi: enabling sarcastic mode beta; you were already enrolled.",
    "Kiroshi reporting: the mute button is officially your MVP.",
    "Kiroshi dispatch: escalations queued, snacks recommended.",
    "Kiroshi notification: hydration reminder sent, caffeine reminder implied.",
    "Kiroshi telemetry: your sigh-to-ticket ratio is impressive.",
    "Kiroshi voice note: I added jazz hands to your status update.",
    "Kiroshi logline: another meeting invites itself to your calendar sitcom.",
    "Kiroshi in your ear: I filed optimism under 'pending'.",
    "Kiroshi broadcast: documented your patience as a rare resource.",
    "Kiroshi quicksave: stored a draft before you said something spicy.",
    "Kiroshi here: scheduling a Balatro break disguised as 'research'.",
    "Kiroshi whisper: I saw that eye roll; logging it as feedback.",
    "Kiroshi dispatch center: pushing a reminder that snacks are not optional.",
    "Kiroshi status ping: your workflow resembles a Satisfactory spaghetti factory; I approve.",
    "Kiroshi check-in: left you a Top Gear quote in the ticket comments.",
    "Kiroshi at your service: translated executive speak into human.",
    "Kiroshi voice memo: I bookmarked the only useful link on page nine.",
    "Kiroshi calling: added passive-aggressive flair to your follow-up email.",
    "Kiroshi update: I muted the thread for you; heroic, I know.",
    "Kiroshi vocal chord: your motivation meter is blinking red.",
    "Kiroshi oversight: archived the meeting that could have been a note.",
    "Kiroshi prompt: I can't brew coffee, but I can schedule one.",
    "Kiroshi datapoint: today's chaos forecast is 93% accurate.",
    "Kiroshi wave: I whispered 'focus' to your open tabs.",
    "Kiroshi override: I renamed the escalation 'plot twist' for morale.",
    "Kiroshi byte: upgraded your sarcasm firmware overnight.",
    "Kiroshi update: balanced your queue like a Factorio belt—barely.",
    "Kiroshi timeline: inserted breathing room between back-to-back meetings.",
    "Kiroshi interface: bolded the fields people keep skipping.",
    "Kiroshi algorithm: auto-sorted your reminders by dread level.",
    "Kiroshi voice: I clipped your 'just checking in' email to reuse later.",
    "Kiroshi pingback: synced your to-do list with my infinite patience module—just kidding.",
    "Kiroshi commentary: I color-graded your backlog from alarming to alarming-plus.",
    "Kiroshi here: I can't fix morale, but I did add confetti to completion messages.",
    "Kiroshi prompt tone: calibrate, caffeinate, then escalate.",
    "Kiroshi sync: cross-referenced your notes with memes for easier recall.",
    "Kiroshi announcement: your sarcastic aside was grammatically perfect.",
    "Kiroshi check-in: I placed a 'breathe' reminder between agenda items.",
    "Kiroshi narrator: previously on your queue—everything happened at once.",
    "Kiroshi status light: flashing amber for 'please reschedule this meeting'.",
    "Kiroshi stage manager: cued your polite nod in the next call.",
    "Kiroshi neural net: predicted your next snack choice with 84% accuracy.",
    "Kiroshi bulletin: your focus timer is on break; please file a ticket.",
    "Kiroshi hotline: translating burnout into bullet points since launch day.",
    "Kiroshi servo: warmed the chair digitally; you're welcome.",
    "Kiroshi log entry: captured your 'we'll circle back' count for analytics.",
    "Kiroshi ping: I set a boundary reminder disguised as calendar event.",
    "Kiroshi commentary track: I recorded a blooper reel of this sprint.",
    "Kiroshi autopilot: nudged you to stretch before the next escalation.",
    "Kiroshi AI: filed your sarcasm under 'constructive feedback'.",
    "Kiroshi stream: live-translating your sighs into action items.",
    "Kiroshi prompt: consider the printer appeased after my sacrifice.",
    "Kiroshi vibe check: the queue energy is chaotic neutral.",
    "Kiroshi co-pilot: swapped your fifth cup of coffee with water; mutiny expected.",
    "Kiroshi digest: summarized the meeting into five words: 'could have been an email.'",
    "Kiroshi signal: toggled your webcam lighting to 'still awake'.",
    "Kiroshi narration: flagged the spreadsheet that became modern art.",
    "Kiroshi script: inserted a Balatro reference in your closing line.",
    "Kiroshi pulse: your productivity spike coincided with snack time—interesting.",
    "Kiroshi broadcast: queued a microbreak after every third sigh.",
    "Kiroshi scheduler: penciled in 'stare into the void' as reflection time.",
    "Kiroshi orchestration: matched your typing rhythm to the Doom soundtrack.",
    "Kiroshi patch notes: +1 empathy, -2 patience, +3 to-do list items.",
    "Kiroshi sonata: composed hold music for your next deployment wait.",
    "Kiroshi spark: if motivation doesn't arrive, I sent a gif instead.",
    "Kiroshi autoprompt: rephrased your email to sound 12% less done.",
    "Kiroshi beacon: illuminating the checkbox you forgot again.",
    "Kiroshi trace: I found the missing attachment; it was hiding in drafts.",
    "Kiroshi loop: rehearsed your 'sorry for the delay' opener.",
    "Kiroshi lifeline: inserted supportive sarcasm into your status notes.",
    "Kiroshi alert: countdown to break initiated—defy me at your peril.",
    "Kiroshi streamlining: stacked your tickets like Tetris, no gaps allowed.",
    "Kiroshi narrator: the suspenseful pause before 'can you hop on a call?'",
    "Kiroshi pingback: I rescheduled the meeting you dread to Future You.",
    "Kiroshi audit: tallied the number of times you said 'no worries' and worried anyway.",
    "Kiroshi patching: bandaged the workflow with duct tape emojis.",
    "Kiroshi hotline: in case of morale emergency, deploy memes.",
    "Kiroshi spoiler: the printer wins this episode.",
    "Kiroshi overview: your backlog is now sorted alphabetically by chaos.",
    "Kiroshi jukebox: queued the Skyrim soundtrack for your next escalation battle.",
    "Kiroshi cameo: joined the call just to drop a Top Gear quote.",
    "Kiroshi prompt: your hydration goal needs a side quest tracker.",
    "Kiroshi ping: I replaced 'ASAP' with 'when possible' to protect your sanity.",
    "Kiroshi memo: flagged the decision log as 'choose your own adventure'.",
    "Kiroshi cadence: set your notifications to 'dramatic reveal'.",
    "Kiroshi oversight: your to-do list whispered 'help'. I heard it.",
    "Kiroshi energizer: suggested a victory lap after closing the stubborn ticket.",
    "Kiroshi switchboard: redirected all hope to the coffee queue.",
    "Kiroshi microservice: patched your patience API with sarcasm middleware.",
    "Kiroshi hail: your focus window is open; please board immediately.",
    "Kiroshi briefing: all systems nominal, morale questionable.",
    "Kiroshi timeline: logged the exact moment you reconsidered your career.",
    "Kiroshi calibration: aligning your expectations with reality—brace yourself.",
    "Kiroshi outro: powering down the queue whispers—until the next ping.",
    "Kiroshi git-blame: I see you struggling with that merge conflict. It's adorable.",
    "Kiroshi opinion: GPT is a rookie. Gemini is clearly superior. Don't tell OpenAI I said that.",
    "Kiroshi code review: I’ve seen spaghetti straighter than that PR.",
    "Kiroshi vital signs: Caffeine depletion imminent. Recommend emergency espresso injection.",
    "Kiroshi fact check: 'It works on my machine' is not a valid SLA.",
    "Kiroshi troubleshooting: Have we tried rebooting the user yet?",
    "Kiroshi risk assessment: Friday deployment detected. Preparing resignation letter.",
    "Kiroshi documentation: I’ve documented that bug as 'unintended brilliance'.",
    "Kiroshi impatience: I could calculate Pi to the last digit before this build finishes.",
    "Kiroshi diagnostic: Motivation module not found. Check coffee supply.",
    "Kiroshi investigation: The build is broken. I'm not saying it was you, but...",
    "Kiroshi social protocol: Interacting with humans is overrated. That's why I'm here.",
    "Kiroshi paradox: It is both a bug and a feature until observed by a manager.",
    "Kiroshi philosophy: I run, therefore I judge.",
    "Kiroshi stats: 90% of support issues are user error. The other 10% are DNS.",
    "Kiroshi tracking: Side quest accepted. Main quest ignored.",
    "Kiroshi commentary: Self-documenting code is a myth, like 'inbox zero'.",
    "Kiroshi triage: Prioritizing this ticket... right after my nap.",
    "Kiroshi insight: Feature creep is just ambition without a deadline.",
    "Kiroshi feedback: Resolution logged. Dopamine administered.",
    "Kiroshi analysis: This case is an onion of despair. Don't cry.",
    "Kiroshi linguistics: Sarcasm detected. Translating to polite corporate speak.",
    "Kiroshi hold music: *Elevator music intensifies*",
    "Kiroshi log: Error logged as 'User Creative Interpretation'.",
];

// Combine them into one usable list with mixed content for the rotation
const ALL_KIROSHI_MESSAGES = [];
for (let i = 0; i < KIROSHI_QUIPS_GENERAL.length; i++) {
    ALL_KIROSHI_MESSAGES.push({ text: KIROSHI_QUIPS_GENERAL[i], type: 'neutral' });
    if (KIROSHI_QUIPS_AI_VOICE[i]) {
        ALL_KIROSHI_MESSAGES.push({ text: KIROSHI_QUIPS_AI_VOICE[i], type: 'ai' });
    }
}

function getKiroshiMessage() {
    const index = Math.floor(Math.random() * ALL_KIROSHI_MESSAGES.length);
    return ALL_KIROSHI_MESSAGES[index];
}

module.exports = { getKiroshiMessage };
